[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
anyhow = "1.0.104"
derive-where = "1.6.1"
eqn-algebra = { path = "crates/eqn-algebra" }
eqn-analysis = { path = "crates/eqn-analysis" }
eqn-core = { path = "crates/eqn-core" }
eqn-macros = { path = "crates/eqn-macros" }
eqn-parser = { path = "crates/eqn-parser" }
eqn-poly = { path = "crates/eqn-poly" }
