use std::num::NonZeroUsize;

use crate::rewriter::Expression;
use crate::ring::{CommutativeRing, PolynomialRing, RingExpr, SemiRing};
use crate::set::Set;
use crate::symbol::Symbol;

type Elem<S> = <<S as SemiRing>::Domain as Set>::Element;

// ================================================================================
// DifferentialAlgebra
// ================================================================================

/// A commutative `k`-algebra `A` generated by symbols, with the partial
/// derivations `∂/∂s` along them: the data the de Rham complex `Ω_{A/k}`
/// needs from its 0-forms. `Self` is the structure `A`; its elements are
/// `<Self::Domain as Set>::Element`, expression trees over the symbols.
/// Choosing canonical representatives of those trees is a [`Rewriter`]'s
/// job, not the algebra's.
///
/// [`Rewriter`]: crate::rewriter::Rewriter
pub trait DifferentialAlgebra:
    CommutativeRing<Domain: Set<Element: Expression<Domain = <Self::Constants as SemiRing>::Domain>>>
{
    /// `k`: the constants.
    type Constants: CommutativeRing;

    /// The structure map `k -> A`.
    fn constant(c: Elem<Self::Constants>) -> Elem<Self>;
    /// The partial inverse of [`constant`](Self::constant): `Some(c)` if `a`
    /// is the image of `c`. Defined on the representation, so meaningful on
    /// normalized trees.
    fn as_constant(a: &Elem<Self>) -> Option<&Elem<Self::Constants>>;
    /// `∂a/∂wrt`. Symbols are independent generators: `∂s/∂t = 0` for `s ≠
    /// t`.
    fn partial(a: Elem<Self>, wrt: &Symbol<<Self::Constants as SemiRing>::Domain>) -> Elem<Self>;
}

// ================================================================================
// PolynomialRing is a DifferentialAlgebra over its own constants
// ================================================================================

/// The polynomial derivation on the raw tree (no normalization -- a
/// [`Rewriter`](crate::rewriter::Rewriter) is the caller's job).
fn partial<R: CommutativeRing>(expr: RingExpr<R>, wrt: &Symbol<R::Domain>) -> RingExpr<R> {
    match expr {
        RingExpr::Const(_) => RingExpr::Const(R::ZERO),
        RingExpr::Symbol(s) => RingExpr::Const(if s == *wrt { R::ONE } else { R::ZERO }),
        RingExpr::Neg(inner) => RingExpr::Neg(Box::new(partial(*inner, wrt))),
        RingExpr::Add(v) => RingExpr::Add(v.into_iter().map(|u| partial(u, wrt)).collect()),
        // Leibniz
        RingExpr::Mul(v) => RingExpr::Add(
            (0..v.len())
                .map(|i| {
                    let mut factors = v.clone();
                    factors[i] = partial(v[i].clone(), wrt);
                    RingExpr::Mul(factors)
                })
                .collect(),
        ),
        RingExpr::Pow { base, exponent } => {
            let d_base = partial((*base).clone(), wrt);
            let reduced = match NonZeroUsize::new(exponent.get() - 1) {
                Some(exponent) => RingExpr::Pow { base, exponent },
                None => RingExpr::Const(R::ONE),
            };
            RingExpr::Mul(vec![
                RingExpr::Const(R::from_usize(exponent.get())),
                reduced,
                d_base,
            ])
        }
    }
}

impl<R: CommutativeRing> DifferentialAlgebra for PolynomialRing<R> {
    type Constants = R;

    fn constant(c: Elem<R>) -> Elem<Self> {
        RingExpr::Const(c)
    }

    fn as_constant(a: &Elem<Self>) -> Option<&Elem<R>> {
        match a {
            RingExpr::Const(c) => Some(c),
            _ => None,
        }
    }

    fn partial(a: Elem<Self>, wrt: &Symbol<R::Domain>) -> Elem<Self> {
        partial(a, wrt)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::rewriter::Rewriter;
    use crate::ring::{CommutativeRingRewriter, IntegerRing, Integers};

    type Expr = RingExpr<IntegerRing>;
    type Alg = PolynomialRing<IntegerRing>;

    fn c(i: i64) -> Expr {
        Expr::Const(i)
    }

    fn xs() -> Symbol<Integers> {
        Symbol::new("x")
    }

    fn ys() -> Symbol<Integers> {
        Symbol::new("y")
    }

    fn x() -> Expr {
        Expr::Symbol(xs())
    }

    fn y() -> Expr {
        Expr::Symbol(ys())
    }

    fn pow(base: Expr, exponent: usize) -> Expr {
        Expr::Pow {
            base: Box::new(base),
            exponent: NonZeroUsize::new(exponent).unwrap(),
        }
    }

    fn norm(e: Expr) -> Expr {
        CommutativeRingRewriter::<IntegerRing>::new().rewrited_expr(e)
    }

    #[test]
    fn partial_of_a_power() {
        // d(x^2)/dx = 2x
        assert_eq!(
            norm(Alg::partial(pow(x(), 2), &xs())),
            Expr::Mul(vec![c(2), x()])
        );
    }

    #[test]
    fn partial_of_a_product() {
        // d(x*y)/dx = y
        assert_eq!(norm(Alg::partial(Expr::Mul(vec![x(), y()]), &xs())), y());
    }

    #[test]
    fn partial_of_a_sum_only_sees_its_own_variable() {
        // d(x^3 + y)/dy = 1
        let expr = Expr::Add(vec![pow(x(), 3), y()]);
        assert_eq!(norm(Alg::partial(expr, &ys())), c(1));
    }

    #[test]
    fn partial_of_a_constant_is_zero() {
        assert_eq!(norm(Alg::partial(c(5), &xs())), c(0));
    }

    #[test]
    fn is_zero_and_is_one_after_normalizing() {
        let zero = norm(Expr::Add(vec![x(), Expr::Neg(Box::new(x()))]));
        assert_eq!(Alg::as_constant(&zero), Some(&IntegerRing::ZERO));

        let one = norm(Expr::Mul(vec![c(1), c(1)]));
        assert_eq!(Alg::as_constant(&one), Some(&IntegerRing::ONE));
    }
}
