use std::num::NonZeroUsize;
use std::ops::{Add, Mul, Neg};

use crate::rewriter::{Expression, Rewriter};
use crate::ring::{CommutativeRing, CommutativeRingRewriter, RingExpr, SemiRing};
use crate::set::Set;
use crate::symbol::Symbol;

// ================================================================================
// DifferentialAlgebra
// ================================================================================

/// A commutative `k`-algebra generated by symbols, with the partial
/// derivations `∂/∂s` along them. This is exactly the data the de Rham
/// complex `Ω_{A/k}` needs from its 0-forms: `k` is [`Constants`], `A` is
/// `Self`. The ring operations are symbolic (they build trees); the
/// canonical form is [`Normalizer`]'s job.
///
/// [`Constants`]: DifferentialAlgebra::Constants
/// [`Normalizer`]: DifferentialAlgebra::Normalizer
pub trait DifferentialAlgebra:
    Expression + Add<Output = Self> + Mul<Output = Self> + Neg<Output = Self>
{
    /// `k`: the constants.
    type Constants: CommutativeRing<Domain = Self::Domain>;
    /// Canonical form of elements of `A`.
    type Normalizer: Rewriter<Expr = Self> + Default;

    /// The image of `c ∈ k` in `A`.
    fn constant(c: <Self::Domain as Set>::Element) -> Self;
    /// `Some(c)` if this element *is* the constant `c`. Meaningful after
    /// normalization.
    fn as_constant(&self) -> Option<&<Self::Domain as Set>::Element>;
    /// `∂self/∂wrt`. Symbols are independent generators: `∂s/∂t = 0` for `s ≠
    /// t`.
    fn partial(self, wrt: &Symbol<Self::Domain>) -> Self;

    // ================================================================================
    // Provided methods
    // ================================================================================

    /// Rewrites `self` into [`Normalizer`](Self::Normalizer)'s canonical form.
    fn normalize(&mut self) {
        Self::Normalizer::default().rewrite_expr(self)
    }

    fn zero() -> Self {
        Self::constant(<Self::Constants as SemiRing>::ZERO)
    }

    fn one() -> Self {
        Self::constant(<Self::Constants as SemiRing>::ONE)
    }

    /// `true` if this element *is* the constant `ZERO`. Meaningful after
    /// normalization.
    fn is_zero(&self) -> bool {
        self.as_constant() == Some(&<Self::Constants as SemiRing>::ZERO)
    }

    /// `true` if this element *is* the constant `ONE`. Meaningful after
    /// normalization.
    fn is_one(&self) -> bool {
        self.as_constant() == Some(&<Self::Constants as SemiRing>::ONE)
    }
}

// ================================================================================
// RingExpr is a DifferentialAlgebra over its own commutative ring
// ================================================================================

impl<R: CommutativeRing> DifferentialAlgebra for RingExpr<R> {
    type Constants = R;
    type Normalizer = CommutativeRingRewriter<R>;

    fn constant(c: <Self::Domain as Set>::Element) -> Self {
        Self::Const(c)
    }

    fn as_constant(&self) -> Option<&<Self::Domain as Set>::Element> {
        match self {
            Self::Const(c) => Some(c),
            _ => None,
        }
    }

    /// The polynomial derivation on the raw tree (no normalization --
    /// [`normalize`](DifferentialAlgebra::normalize) is the caller's job).
    fn partial(self, wrt: &Symbol<Self::Domain>) -> Self {
        match self {
            Self::Const(_) => Self::Const(R::ZERO),
            Self::Symbol(s) => Self::Const(if s == *wrt { R::ONE } else { R::ZERO }),
            Self::Neg(inner) => Self::Neg(Box::new((*inner).partial(wrt))),
            Self::Add(v) => Self::Add(v.into_iter().map(|u| u.partial(wrt)).collect()),
            // Leibniz: d(a_1 * ... * a_n) = sum_i a_1 * ... * (d a_i) * ... * a_n.
            // ponytail: clones the factor list once per factor; fine for the
            // small products expression trees carry.
            Self::Mul(v) => Self::Add(
                (0..v.len())
                    .map(|i| {
                        let mut factors = v.clone();
                        factors[i] = v[i].clone().partial(wrt);
                        Self::Mul(factors)
                    })
                    .collect(),
            ),
            Self::Pow { base, exponent } => {
                let d_base = (*base.clone()).partial(wrt);
                let reduced = match NonZeroUsize::new(exponent.get() - 1) {
                    Some(exponent) => Self::Pow { base, exponent },
                    None => Self::Const(R::ONE),
                };
                Self::Mul(vec![
                    Self::Const(R::from_usize(exponent.get())),
                    reduced,
                    d_base,
                ])
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ring::{IntegerRing, Integers};

    type Expr = RingExpr<IntegerRing>;

    fn c(i: i64) -> Expr {
        Expr::Const(i)
    }

    fn xs() -> Symbol<Integers> {
        Symbol::new("x")
    }

    fn ys() -> Symbol<Integers> {
        Symbol::new("y")
    }

    fn x() -> Expr {
        Expr::Symbol(xs())
    }

    fn y() -> Expr {
        Expr::Symbol(ys())
    }

    fn pow(base: Expr, exponent: usize) -> Expr {
        Expr::Pow {
            base: Box::new(base),
            exponent: NonZeroUsize::new(exponent).unwrap(),
        }
    }

    fn norm(mut e: Expr) -> Expr {
        e.normalize();
        e
    }

    #[test]
    fn partial_of_a_power() {
        // d(x^2)/dx = 2x
        assert_eq!(norm(pow(x(), 2).partial(&xs())), Expr::Mul(vec![c(2), x()]));
    }

    #[test]
    fn partial_of_a_product() {
        // d(x*y)/dx = y
        assert_eq!(norm(Expr::Mul(vec![x(), y()]).partial(&xs())), y());
    }

    #[test]
    fn partial_of_a_sum_only_sees_its_own_variable() {
        // d(x^3 + y)/dy = 1
        let expr = Expr::Add(vec![pow(x(), 3), y()]);
        assert_eq!(norm(expr.partial(&ys())), c(1));
    }

    #[test]
    fn partial_of_a_constant_is_zero() {
        assert_eq!(norm(c(5).partial(&xs())), c(0));
    }

    #[test]
    fn is_zero_and_is_one_after_normalizing() {
        assert!(norm(Expr::Add(vec![x(), -x()])).is_zero());
        assert!(norm(Expr::Mul(vec![c(1), c(1)])).is_one());
    }
}
