use std::fmt;
use std::marker::PhantomData;
use std::ops::{Add, Div, Mul, Neg, Sub};

use crate::algebra::Algebra;
use crate::map::Map;
use crate::module::{Module, ModuleElem, ModuleScalar};
use crate::op::{Associative, BinaryOperator, Commutative, Inverse};
use crate::ring::{Ring, RingElem, Subring};
use crate::set::Set;

// ================================================================================
// Field
// ================================================================================

/// A field: a commutative ring whose multiplication has inverses for every
/// element except `ZERO`. `invert(ZERO)` is a contract violation, not an
/// error; the operator's `Inverse` impl is only consulted for non-zero input.
pub trait Field: Ring<Multiplication: Commutative + Inverse> {
    fn invert(a: RingElem<Self>) -> RingElem<Self> {
        <Self::Multiplication as Inverse>::inverse(a)
    }
}

/// Any ring whose multiplication is commutative and invertible is a field
/// for free.
impl<R> Field for R
where
    R: Ring,
    R::Multiplication: Commutative + Inverse,
{
}

/// A subring of a field that is closed under inversion of nonzero elements.
pub trait Subfield: Subring<Parent: Field> {}

/// A field equipped with a chosen base-field algebra structure.
pub trait FieldExtension: Field + Algebra<Scalars = Self::BaseField> {
    type BaseField: Field;
}

/// A finite-dimensional field extension.
pub trait FiniteExtension: FieldExtension {
    type const DEGREE: usize;
}

/// A field extension generated by algebraic elements.
pub trait AlgebraicExtension: FieldExtension {}

impl<E: FiniteExtension> AlgebraicExtension for E {}

/// An algebraic extension in which every irreducible polynomial having a root
/// splits completely.
pub trait NormalExtension: AlgebraicExtension {}

/// An algebraic extension whose elements have separable minimal polynomials.
pub trait SeparableExtension: AlgebraicExtension {}

/// An extension that is both normal and separable.
pub trait GaloisExtension: NormalExtension + SeparableExtension {}

impl<E> GaloisExtension for E where E: NormalExtension + SeparableExtension {}

/// A splitting field for the polynomial represented by `P`.
pub trait SplittingField<P>: NormalExtension {
    fn roots() -> Vec<RingElem<Self>>;
}

/// A unital field homomorphism from `D` to `C`.
pub trait FieldHomomorphism<D: Field, C: Field>: Map<D::Domain, C::Domain> {}

/// A field homomorphism, which is necessarily injective.
pub trait FieldEmbedding<D: Field, C: Field>: FieldHomomorphism<D, C> {}

impl<T, D, C> FieldEmbedding<D, C> for T
where
    D: Field,
    C: Field,
    T: FieldHomomorphism<D, C>,
{
}

/// Element alias for the base field of an extension.
pub type BaseFieldElem<E> = RingElem<<E as FieldExtension>::BaseField>;

/// The finite prime field `F_p`.
///
/// `P` is part of the algebraic contract: it must be prime.
pub struct PrimeField<const P: u64>(PhantomData<PrimeFieldSet<P>>);

impl<const P: u64> PrimeField<P> {
    /// TODO: Use a faster primality test algorithm
    /// Thought of using Miller-Rabin, but a slight problem is to define the
    /// bounds on determining how many primes to test
    pub const fn is_valid() -> bool {
        if P < 2 {
            return false;
        }
        let mut divisor = 2;
        while divisor <= P / divisor {
            if P.is_multiple_of(divisor) {
                return false;
            }
            divisor += 1;
        }
        true
    }

    pub const fn assert_valid() {
        assert!(Self::is_valid(), "prime-field characteristic must be prime");
    }
}

/// An element of [`PrimeField<P>`].
#[derive(Clone, Copy, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct PrimeFieldElement<const P: u64> {
    value: u64,
}

/// TODO: Implement as bignum
impl<const P: u64> PrimeFieldElement<P> {
    pub const ZERO: Self = Self { value: 0 };
    pub const ONE: Self = Self { value: 1 };

    pub fn new(value: u64) -> Self {
        PrimeField::<P>::assert_valid();
        Self { value: value % P }
    }

    /// TODO: Implement as bignum
    pub fn from_i64(value: i64) -> Self {
        PrimeField::<P>::assert_valid();
        let modulus = i128::from(P);
        let value = i128::from(value).rem_euclid(modulus) as u64;
        Self { value }
    }

    /// TODO: Implement as bignum
    pub const fn value(self) -> u64 {
        self.value
    }

    pub const fn is_zero(self) -> bool {
        self.value == 0
    }

    pub fn pow(self, mut exponent: u64) -> Self {
        let mut acc = Self::ONE;
        let mut base = self;
        while exponent > 0 {
            if exponent & 1 == 1 {
                acc = acc * base;
            }
            exponent >>= 1;
            if exponent > 0 {
                base = base * base;
            }
        }
        acc
    }

    pub fn inverse(self) -> Self {
        PrimeField::<P>::assert_valid();
        assert!(!self.is_zero(), "zero has no multiplicative inverse");
        self.pow(P - 2)
    }

    fn product(self, rhs: Self) -> Self {
        PrimeField::<P>::assert_valid();
        let value = (u128::from(self.value) * u128::from(rhs.value)) % u128::from(P);
        Self {
            value: value as u64,
        }
    }
}

impl<const P: u64> fmt::Debug for PrimeFieldElement<P> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_tuple("PrimeFieldElement")
            .field(&self.value)
            .finish()
    }
}

impl<const P: u64> From<u64> for PrimeFieldElement<P> {
    fn from(value: u64) -> Self {
        Self::new(value)
    }
}

impl<const P: u64> From<i64> for PrimeFieldElement<P> {
    fn from(value: i64) -> Self {
        Self::from_i64(value)
    }
}

impl<const P: u64> Add for PrimeFieldElement<P> {
    type Output = Self;

    fn add(self, rhs: Self) -> Self {
        PrimeField::<P>::assert_valid();
        let value = (u128::from(self.value) + u128::from(rhs.value)) % u128::from(P);
        Self {
            value: value as u64,
        }
    }
}

impl<const P: u64> Sub for PrimeFieldElement<P> {
    type Output = Self;

    fn sub(self, rhs: Self) -> Self {
        self + -rhs
    }
}

impl<const P: u64> Neg for PrimeFieldElement<P> {
    type Output = Self;

    fn neg(self) -> Self {
        PrimeField::<P>::assert_valid();
        if self.is_zero() {
            self
        } else {
            Self {
                value: P - self.value,
            }
        }
    }
}

impl<const P: u64> Mul for PrimeFieldElement<P> {
    type Output = Self;

    fn mul(self, rhs: Self) -> Self {
        self.product(rhs)
    }
}

impl<const P: u64> Div for PrimeFieldElement<P> {
    type Output = Self;

    fn div(self, rhs: Self) -> Self {
        self.product(rhs.inverse())
    }
}

/// The set underlying [`PrimeField<P>`].
#[derive(Set)]
#[set(element = PrimeFieldElement<P>)]
pub struct PrimeFieldSet<const P: u64>(PhantomData<PrimeField<P>>);

#[derive(Associative, BinaryOperator, Commutative)]
#[operator(domain = PrimeFieldSet<P>, apply = Add::add, identity = PrimeFieldElement::ZERO, inverse = Neg::neg)]
pub struct PrimeFieldAdd<const P: u64>(PhantomData<PrimeField<P>>);

#[derive(Associative, BinaryOperator, Commutative)]
#[operator(domain = PrimeFieldSet<P>, apply = Mul::mul, identity = PrimeFieldElement::ONE, inverse = |a| a.inverse())]
pub struct PrimeFieldMul<const P: u64>(PhantomData<PrimeField<P>>);

impl<const P: u64> crate::ring::SemiRing for PrimeField<P> {
    type Domain = PrimeFieldSet<P>;
    type Addition = PrimeFieldAdd<P>;
    type Multiplication = PrimeFieldMul<P>;
}

impl<const P: u64> Module for PrimeField<P> {
    type Scalars = Self;
    type Domain = PrimeFieldSet<P>;
    type Addition = PrimeFieldAdd<P>;

    fn scale(scalar: ModuleScalar<Self>, value: ModuleElem<Self>) -> ModuleElem<Self> {
        scalar * value
    }
}

impl<const P: u64> FieldExtension for PrimeField<P> {
    type BaseField = Self;
}

impl<const P: u64> FiniteExtension for PrimeField<P> {
    type const DEGREE: usize = 1;
}

impl<const P: u64> NormalExtension for PrimeField<P> {}
impl<const P: u64> SeparableExtension for PrimeField<P> {}

#[cfg(test)]
mod tests {
    use eqn_core::set::{Q, Rational};

    use super::*;
    use crate::operator_impl::{QAdd, QMul};
    use crate::ring::{CommutativeRing, SemiRing, SubSemiRing};

    type Rationals = (Q, QAdd, QMul);

    struct AllRationals;

    impl SubSemiRing for AllRationals {
        type Parent = Rationals;

        fn contains(_: &RingElem<Self::Parent>) -> bool {
            true
        }
    }

    impl Subring for AllRationals {}
    impl Subfield for AllRationals {}

    #[test]
    fn rationals_form_a_subfield() {
        fn assert_subfield<S: Subfield>() {}

        assert_subfield::<AllRationals>();
        for value in [Rational::from(-3), Rational::from(1), Rational::from(4)] {
            assert!(AllRationals::contains(&Rationals::invert(value)));
        }
    }

    #[test]
    fn prime_field_elements_normalize_residues() {
        type F5 = PrimeFieldElement<5>;

        assert_eq!(F5::new(7).value(), 2);
        assert_eq!(F5::from_i64(-1).value(), 4);
        assert_eq!(F5::from_i64(-13).value(), 2);
    }

    #[test]
    fn prime_field_arithmetic_is_modulo_p() {
        type F5 = PrimeField<5>;
        type E = PrimeFieldElement<5>;

        assert_eq!(F5::add(E::new(3), E::new(4)), E::new(2));
        assert_eq!(F5::negate(E::new(2)), E::new(3));
        assert_eq!(F5::multiply(E::new(3), E::new(4)), E::new(2));
        assert_eq!(F5::invert(E::new(2)), E::new(3));
        assert_eq!(E::new(3) - E::new(4), E::new(4));
        assert_eq!(E::new(3) / E::new(2), E::new(4));
    }

    #[test]
    fn prime_fields_are_galois_extensions() {
        fn assert_galois<E: GaloisExtension>() {}

        assert_galois::<PrimeField<5>>();
    }

    #[test]
    fn every_nonzero_prime_field_element_has_an_inverse() {
        type F7 = PrimeField<7>;
        type E = PrimeFieldElement<7>;

        for value in 1..7 {
            let x = E::new(value);
            assert_eq!(F7::multiply(x, F7::invert(x)), F7::ONE);
        }
    }

    #[test]
    #[should_panic(expected = "prime-field characteristic must be prime")]
    fn composite_characteristics_fail_fast() {
        PrimeField::<4>::multiply(PrimeFieldElement::ONE, PrimeFieldElement::ONE);
    }

    #[test]
    fn prime_fields_expose_ring_module_algebra_and_extension_structure() {
        fn assert_commutative_ring<R: CommutativeRing>() {}
        fn assert_field<F: Field>() {}
        fn assert_module<M: Module>() {}
        fn assert_algebra<A: Algebra>() {}
        fn assert_field_extension<E: FieldExtension<BaseField = E>>() {}
        fn assert_finite_extension<E: FiniteExtension>() {}
        fn assert_algebraic_extension<E: AlgebraicExtension>() {}

        type F5 = PrimeField<5>;
        type E = PrimeFieldElement<5>;

        assert_commutative_ring::<F5>();
        assert_field::<F5>();
        assert_module::<F5>();
        assert_algebra::<F5>();
        assert_field_extension::<F5>();
        assert_finite_extension::<F5>();
        assert_algebraic_extension::<F5>();

        assert_eq!(F5::ZERO, E::ZERO);
        assert_eq!(F5::ONE, E::ONE);
        assert_eq!(F5::from_scalar(E::new(3)), E::new(3));
        assert_eq!(F5::scale(E::new(3), E::new(4)), E::new(2));
        assert_eq!(F5::DEGREE, 1);
    }
}
