use std::fmt;
use std::ops::{Add, Div, Mul, Neg, Sub};
use std::str::FromStr;

use eqn_core::map::Map;
use eqn_core::op::{Associative, BinaryOperator, Commutative, Inverse};
use eqn_core::set::Set;

use crate::algebra::Algebra;
use crate::ring::{Ring, RingElem, Subring};

// ================================================================================
// Field
// ================================================================================

/// A field: a commutative ring whose multiplication has inverses for every
/// element except `zero()`. `invert(zero())` is a contract violation, not an
/// error; the operator's `Inverse` impl is only consulted for non-zero input.
pub trait Field: Ring<Multiplication: Commutative + Inverse> {
    /// Source spelling of division.
    const DIV_SYMBOL: &'static str = <Self::Multiplication as Inverse>::INVERSE_SYMBOL;

    fn invert(a: RingElem<Self>) -> RingElem<Self> {
        <Self::Multiplication as Inverse>::inverse(a)
    }
}

/// Any ring whose multiplication is commutative and invertible is a field
/// for free.
impl<R> Field for R
where
    R: Ring,
    R::Multiplication: Commutative + Inverse,
{
}

/// A subring of a field that is closed under inversion of nonzero elements.
pub trait Subfield: Subring<Parent: Field> {}

/// A field equipped with a chosen base-field algebra structure.
pub trait FieldExtension: Field + Algebra<Scalars = Self::BaseField> {
    type BaseField: Field;
}

/// A finite-dimensional field extension.
pub trait FiniteExtension: FieldExtension {
    const DEGREE: usize;
}

/// A field extension generated by algebraic elements.
pub trait AlgebraicExtension: FieldExtension {}

impl<E: FiniteExtension> AlgebraicExtension for E {}

/// An algebraic extension in which every irreducible polynomial having a root
/// splits completely.
pub trait NormalExtension: AlgebraicExtension {}

/// An algebraic extension whose elements have separable minimal polynomials.
pub trait SeparableExtension: AlgebraicExtension {}

/// An extension that is both normal and separable.
pub trait GaloisExtension: NormalExtension + SeparableExtension {}

impl<E> GaloisExtension for E where E: NormalExtension + SeparableExtension {}

/// A splitting field for the polynomial represented by `P`.
pub trait SplittingField<P>: NormalExtension {
    fn roots() -> Vec<RingElem<Self>>;
}

/// A unital field homomorphism from `D` to `C`.
pub trait FieldHomomorphism<D: Field, C: Field>: Map<D::Domain, C::Domain> {}

/// A field homomorphism, which is necessarily injective.
pub trait FieldEmbedding<D: Field, C: Field>: FieldHomomorphism<D, C> {}

impl<T, D, C> FieldEmbedding<D, C> for T
where
    D: Field,
    C: Field,
    T: FieldHomomorphism<D, C>,
{
}

/// Element alias for the base field of an extension.
pub type BaseFieldElem<E> = RingElem<<E as FieldExtension>::BaseField>;

/// A residue modulo the prime `P`. The type is the set `F_p`;
/// [`PrimeField<P>`] is its field structure.
#[derive(Clone, Copy, Eq, Hash, Ord, PartialEq, PartialOrd, Set)]
pub struct Fp<const P: u64> {
    value: u64,
}

/// TODO: Implement as bignum
impl<const P: u64> Fp<P> {
    /// TODO: Use a faster primality test algorithm
    /// Thought of using Miller-Rabin, but a slight problem is to define the
    /// bounds on determining how many primes to test
    pub const fn is_valid() -> bool {
        if P < 2 {
            return false;
        }
        let mut divisor = 2;
        while divisor <= P / divisor {
            if P.is_multiple_of(divisor) {
                return false;
            }
            divisor += 1;
        }
        true
    }

    pub const fn assert_valid() {
        assert!(Self::is_valid(), "prime-field characteristic must be prime");
    }

    pub const fn zero() -> Self {
        Self { value: 0 }
    }

    pub const fn one() -> Self {
        Self { value: 1 }
    }

    pub fn new(value: u64) -> Self {
        Self::assert_valid();
        Self { value: value % P }
    }

    /// TODO: Implement as bignum
    pub fn from_i64(value: i64) -> Self {
        Self::assert_valid();
        let modulus = i128::from(P);
        let value = i128::from(value).rem_euclid(modulus) as u64;
        Self { value }
    }

    /// TODO: Implement as bignum
    pub const fn value(self) -> u64 {
        self.value
    }

    pub const fn is_zero(self) -> bool {
        self.value == 0
    }

    pub fn pow(self, mut exponent: u64) -> Self {
        let mut acc = Self::one();
        let mut base = self;
        while exponent > 0 {
            if exponent & 1 == 1 {
                acc = acc * base;
            }
            exponent >>= 1;
            if exponent > 0 {
                base = base * base;
            }
        }
        acc
    }

    pub fn inverse(self) -> Self {
        Self::assert_valid();
        assert!(!self.is_zero(), "zero has no multiplicative inverse");
        self.pow(P - 2)
    }

    fn product(self, rhs: Self) -> Self {
        Self::assert_valid();
        let value = (u128::from(self.value) * u128::from(rhs.value)) % u128::from(P);
        Self {
            value: value as u64,
        }
    }
}

impl<const P: u64> fmt::Debug for Fp<P> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_tuple("Fp").field(&self.value).finish()
    }
}

impl<const P: u64> From<u64> for Fp<P> {
    fn from(value: u64) -> Self {
        Self::new(value)
    }
}

impl<const P: u64> From<i64> for Fp<P> {
    fn from(value: i64) -> Self {
        Self::from_i64(value)
    }
}

/// Reads an integer, reduced modulo `P`; negative values are allowed.
impl<const P: u64> FromStr for Fp<P> {
    type Err = std::num::ParseIntError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.parse::<u64>() {
            Ok(value) => Ok(Self::new(value)),
            Err(_) => s.parse::<i64>().map(Self::from_i64),
        }
    }
}

impl<const P: u64> Add for Fp<P> {
    type Output = Self;

    fn add(self, rhs: Self) -> Self {
        Self::assert_valid();
        let value = (u128::from(self.value) + u128::from(rhs.value)) % u128::from(P);
        Self {
            value: value as u64,
        }
    }
}

impl<const P: u64> Sub for Fp<P> {
    type Output = Self;

    fn sub(self, rhs: Self) -> Self {
        self + -rhs
    }
}

impl<const P: u64> Neg for Fp<P> {
    type Output = Self;

    fn neg(self) -> Self {
        Self::assert_valid();
        if self.is_zero() {
            self
        } else {
            Self {
                value: P - self.value,
            }
        }
    }
}

impl<const P: u64> Mul for Fp<P> {
    type Output = Self;

    fn mul(self, rhs: Self) -> Self {
        self.product(rhs)
    }
}

impl<const P: u64> Div for Fp<P> {
    type Output = Self;

    fn div(self, rhs: Self) -> Self {
        self.product(rhs.inverse())
    }
}

#[derive(Associative, BinaryOperator, Commutative)]
#[operator(domain = Fp<P>, symbol = "+", apply = Add::add, identity = Fp::zero(), inverse = Neg::neg, inverse_symbol = "-")]
pub struct FpAdd<const P: u64>;

#[derive(Associative, BinaryOperator, Commutative)]
#[operator(domain = Fp<P>, symbol = "*", apply = Mul::mul, identity = Fp::one(), inverse = |a| a.inverse(), inverse_symbol = "/")]
pub struct FpMul<const P: u64>;

<<<<<<< HEAD
/// The finite prime field `F_p`: the tuple of its operations.
///
/// `P` is part of the algebraic contract: it must be prime.
pub type PrimeField<const P: u64> = (FpAdd<P>, FpMul<P>);

#[cfg(test)]
mod tests {
    use eqn_core::set::{Q, Subset};

    use super::*;
    use crate::operator_impl::{QAdd, QMul};
    use crate::ring::{SemiRing, SubSemiRing};

    type Rationals = (QAdd, QMul);

    struct AllRationals;

    impl Subset for AllRationals {
        type Superset = Q;

        fn contains(_: &Q) -> bool {
            true
        }
    }

    impl SubSemiRing for AllRationals {
        type Parent = Rationals;
    }

    impl Subring for AllRationals {}
    impl Subfield for AllRationals {}

    #[test]
    fn rationals_form_a_subfield() {
        fn assert_subfield<S: Subfield>() {}

        assert_subfield::<AllRationals>();
        for value in [Q::from(-3), Q::from(1), Q::from(4)] {
            assert!(AllRationals::contains(&Rationals::invert(value)));
        }
    }

    #[test]
    fn prime_field_elements_normalize_residues() {
        type F5 = Fp<5>;

        assert_eq!(F5::new(7).value(), 2);
        assert_eq!(F5::from_i64(-1).value(), 4);
        assert_eq!(F5::from_i64(-13).value(), 2);
    }

    #[test]
    fn prime_field_elements_parse_modulo_p() {
        type E = Fp<5>;

        assert_eq!("7".parse::<E>().unwrap(), E::new(2));
        assert_eq!("-1".parse::<E>().unwrap(), E::new(4));
        assert!("x".parse::<E>().is_err());
    }

    #[test]
    fn prime_field_arithmetic_is_modulo_p() {
        type F5 = PrimeField<5>;
        type E = Fp<5>;

        assert_eq!(F5::add(E::new(3), E::new(4)), E::new(2));
        assert_eq!(F5::negate(E::new(2)), E::new(3));
        assert_eq!(F5::multiply(E::new(3), E::new(4)), E::new(2));
        assert_eq!(F5::invert(E::new(2)), E::new(3));
        assert_eq!(E::new(3) - E::new(4), E::new(4));
        assert_eq!(E::new(3) / E::new(2), E::new(4));
    }

    #[test]
    fn every_nonzero_prime_field_element_has_an_inverse() {
        type F7 = PrimeField<7>;
        type E = Fp<7>;

        for value in 1..7 {
            let x = E::new(value);
            assert_eq!(F7::multiply(x, F7::invert(x)), F7::one());
        }
    }

    #[test]
    #[should_panic(expected = "prime-field characteristic must be prime")]
    fn composite_characteristics_fail_fast() {
        PrimeField::<4>::multiply(Fp::one(), Fp::one());
    }

    #[test]
    fn prime_fields_are_fields() {
        fn assert_field<F: Field>() {}

        type F5 = PrimeField<5>;
        type E = Fp<5>;

        assert_field::<F5>();
        assert_eq!(F5::zero(), E::zero());
        assert_eq!(F5::one(), E::one());
    }
}
